DROP TABLE IF EXISTS ADDRESSES;

CREATE TABLE ADDRESSES (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
STREET VARCHAR(100) NOT NULL,
NUMBER INT NOT NULL,
CITY VARCHAR(100) NOT NULL,
PROVINCE VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS PATIENTS;

CREATE TABLE PATIENTS (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
LASTNAME VARCHAR(100) NOT NULL,
FIRSTNAME VARCHAR(100) NOT NULL,
EMAIL VARCHAR(100) NOT NULL,
DNI INT NOT NULL,
ADMISSION_DATE DATE NOT NULL,
ADDRESS_ID INT NOT NULL
);

DROP TABLE IF EXISTS DENTISTS;

CREATE TABLE DENTISTS (
ID BIGINT AUTO_INCREMENT PRIMARY KEY,
LASTNAME VARCHAR(100) NOT NULL,
FIRSTNAME VARCHAR(100) NOT NULL,
PROFESSIONAL_ID INT NOT NULL
);

INSERT INTO ADDRESSES (STREET, NUMBER, CITY, PROVINCE) VALUES
('Roca', 364, 'Rosario', 'Santa Fe'),
('Carlos Ayala', 196, 'Formosa', 'Formosa');

INSERT INTO PATIENTS (LASTNAME, FIRSTNAME, EMAIL, DNI, ADMISSION_DATE, ADDRESS_ID) VALUES
('Gonzalez', 'Araceli', 'ara@gmail.com', 1231233, '2022-06-14', 1),
('Gimenez', 'Emi', 'emi@gmail.com', 1234567, '2022-06-14', 2);

INSERT INTO DENTISTS (LASTNAME, FIRSTNAME, PROFESSIONAL_ID) VALUES
('Ortiz', 'Patricia', 1234);
